apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  # The Pods template
  template:  
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: vprofile/vprofiledb:v1
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: vpro-db-data

        ports:
          - name: vprodb-port
            containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              name: app-secret
              key: db-pass
      nodeSelector:
        zone: us-east-2a

      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
          volumeID: vol-01ead551add2f7dcc
          fsType: ext4

      initContainers:
        - name: busybox
          image: busybox:latest
          args: ["rm","-rf","/var/lib/mysql/lost_found"]
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: vpro-db-data        

            
                
